### ISSUE TITLE
Unhandled Exception for null actions

### ISSUE THREAD

**Issue by nikunjbhartia** [wit-ai/wit-ruby#11]
> ruby examples/quickstart.rb TOZOS7QIT6TUQXOK326CU2LPGVZ4VG2K
> hello
> I, [2016-05-10T13:15:28.446386 #6346]  INFO -- : Executing merge
> /var/lib/gems/2.1.0/gems/wit-3.3.1/lib/wit.rb:112:in `run_actions_': undefined method`to_sym' for nil:NilClass (NoMethodError)
>     from /var/lib/gems/2.1.0/gems/wit-3.3.1/lib/wit.rb:128:in `run_actions_'
>     from /var/lib/gems/2.1.0/gems/wit-3.3.1/lib/wit.rb:133:in`run_actions'
>     from /var/lib/gems/2.1.0/gems/wit-3.3.1/lib/wit.rb:144:in `interactive'
>     from examples/quickstart.rb:37:in`<main>'

**Comment by patapizza** [comment]
Do you still experience the issue?

I get "Can we know the price range you are looking for ?"

**Comment by nikunjbhartia** [comment]
Yes, I still get it
I had made a pull request with the changed code.I can't find it there now

**Comment by nikunjbhartia** [comment]
I have made the pull request again., this error will always trigger when you start the script with a totally new app and there is no training being done.
You can replicate this by trying it on a fresh app, mine has a trained story already hence you dont get the error.

**Comment by patapizza** [comment]
I get `HTTP error code=404 (WitException)` when trying on a fresh, untrained app (model not found).
Can you set the log level to `DEBUG` and show the output?

Thank you

**Comment by blandinw** [comment]
I consider this issue either fixed or obsolete, closing but feel free to reopen :-)
