### ISSUE TITLE
Slight confusion with converse and mixed responses

### ISSUE THREAD

**Issue by SylarRuby** [wit-ai/wit-ruby#19]
When I:

    rsp = client.message('I need to add two numbers')

I get a response by asking the user a question, then I send to wit the reply:

    rsp = client.converse('<what-is this...really?', 'two and two', {})

Two things happened here:

If the user replies within few seconds, my rsp will have `"type" => "msg",`, if the user takes long to reply, say 1min, my rsp will be `"type" => "action",`. I'm lost. Why not include a session id with all message responses? Am I conversing properly? I'm lost with that "unique_session_id". Is that some random string generated by the my server? If so, why?

**Comment by peteygao** [comment]
Yes, it should be a random (and unique) token generated by your server, it's how Wit.ai tracks a conversation on their end (and how you can track it in your app too, if you need to!).

Think of it as a Web Session that's in a browser cookie to determine if you're logged in.

Imagine the following scenario where you have two users, Bob and Alice, conversing with Wit.ai in your app:
```
Alice: "What's the weather in Paris?"
Bob: "What's the weather in Tokyo?"
```

How should Wit.ai respond? Without a unique session token, there's no way for Wit to know to send Paris' weather to Alice, and Tokyo's weather to Bob. But with that token, it can uniquely identify which user said what.
