### ISSUE TITLE
Converse api type response is always value

### ISSUE THREAD

**Issue by M-Younes** [wit-ai/wit-ruby#21]
Hello guys,
Let's say I have this story:
Users says: Bye
Bot says: Have a good one!
Bots says: ByeBye

it work in the wit testing dashboard.
Now when I'm trying to get that by converse method repeatedly till I get the type stop, but the type is always "value"
client.converse("session_id", "Bye") returns 
`{"confidence"=>0.0010324002873500187, "type"=>"msg", "msg"=>"Have a good one!", "entities"=>{"goodbye"=>[{"confidence"=>0.9514085768812446, "type"=>"value", "value"=>"Bye"}]}}`
 and then I do it again it returns:
`{"confidence"=>0.0008932824968469721, "type"=>"msg", "msg"=>"ByeBye", "entities"=>{"goodbye"=>[{"confidence"=>0.9514085768812446, "type"=>"value", "value"=>"Bye"}]}}`

I tried passing the session as an empty hash for the first call and then fill it in with entities for the second time but nothing changes.

Pls help 

Thanks

**Comment by aforaleka** [comment]
Closing the issue since we have sunsetted converse.
