### ISSUE TITLE
Examples use deprecated actions hash

### ISSUE THREAD

**Issue by Awem** [wit-ai/wit-ruby#25]
According to 57bdeb4bcdf6994e8dda76d7cb18a9ff833186a4, the `actions` hash is deprecated for `Wit.new`. However, the examples still use it. Please update the examples, because to me there is no clear  migration plan. There are only very general advices in https://wit.ai/blog/2017/07/27/sunsetting-stories

**Comment by blandinw** [comment]
Thank you for your feedback, you're right, we'll update the examples.

**Comment by aforaleka** [comment]
Closing this issue since we've updated the examples.
