### ISSUE TITLE
224

### ISSUE THREAD

**Issue by Gawad-W** [wit-ai/wit-ruby#32]
,
 >  حذف ,
 >  حذف ریلیم ,
 >  قوانین ,
 >  توضیحات ,
 >  تنظیم نام    ,
  > تنظیم عکس ,
  > ترفیع    ,
  > تنزل  ,
  > راهنما ,
  > پاک کردن    ,
  > kill chat ,
  > kill realm ,
  > تنزل    ,
  > تنزل  ,
  > تنظیم      ,
  > قفل    ,
  > دارنده  ,
  > دارنده  ,
  > صاحب ,
  > آیدی    ,
  > صاحب   ,
  > باز کردن    ,
  > تنظیم حساسیت  ,
  > تنظیمات ,
  > لیست مدیران ,
  > لینک جدید ,
  > لینک ,
  > لینک خصوصی ,
  > حذف غیرفعالین ,
  > حذف غیرفعالین  ,

**Comment by dupengling** [comment]
Hi @Gawad-W, can you explain what the issue is?

**Comment by Gawad-W** [comment]
حذف ریپلم

**Comment by Gawad-W** [comment]
حذف ,

**Comment by Gawad-W** [comment]
توضیحات ,

**Comment by Gawad-W** [comment]
راهنما ,

**Comment by Gawad-W** [comment]
تنزل ,

**Comment by Gawad-W** [comment]
صاحب ,علی

**Comment by Gawad-W** [comment]
لیست مدیران ,ad24metre

**Comment by Gawad-W** [comment]
لینک ,https://t.me/joinchat/Dtb3aU-7RaZBzO9uF3jhgg

**Comment by Gawad-W** [comment]
تنظیم حساسیت ,@,http,https,www.,ات ساین،فروارد,bot

**Comment by Gawad-W** [comment]
2841365q

**Comment by Gawad-W** [comment]
,kill chat

**Comment by Gawad-W** [comment]
آیدی ,@ad24metre

**Comment by Gawad-W** [comment]
صاحب ,@agan90

**Comment by Gawad-W** [comment]
[]()

**Comment by Gawad-W** [comment]
@Gawad-W

**Comment by Gawad-W** [comment]
سفارش  ممبر وفالوور لایک،سین،شماره های مجازی ،ساخت ربات تبچی وضد لینگ به ایدی زیردر تلگرام   مراجعه کنید                                    ad24metre@

**Comment by Gawad-W** [comment]
ادرس گروه تبلیغات رایگان 
@a24metre1

**Comment by Gawad-W** [comment]
@Gawad-W Gawad-W

**Comment by Gawad-W** [comment]
panel

**Comment by Gawad-W** [comment]
comment

**Comment by Gawad-W** [comment]
ترک کردن

**Comment by Gawad-W** [comment]
🆔️   @ad24metre

**Comment by Gawad-W** [comment]
224#32

**Comment by Gawad-W** [comment]
224#32
