### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by Sciff** [wit-ai/wit-ruby#6]
WitException: The 'say' action should take 3 arguments: session_id, context, msg. 
WitException: The 'error' action should take 3 arguments: session_id, context, error.

actions = {
  :say => -> (session_id, msg) {
    p msg
  },
  :merge => -> (session_id, context, entities, msg) {
    return context
  },
  :error => -> (session_id, context) {
    p 'Oops I don\'t know what to do.'
  },
}
should be 
actions = {
  :say => -> (session_id, context, msg) {
    p msg
  },
  :merge => -> (session_id, context, entities, msg) {
    return context
  },
  :error => -> (session_id, context, error) {
    p 'Oops I don\'t know what to do.'
  },
}

**Comment by patapizza** [comment]
Thanks, fixed!
